### ISSUE TITLE
Create Class from CSV.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/advanced_ruby#6]
https://github.com/osifoanosike/advanced_ruby/tree/master/CreateClassFromCSV

**Comment by mkangia** [comment]
Osifo: Lets take care of few things in general : 
1) put the solution link in description and not in title of the issue.
2) indentation to be done with spaces and not tabs. What tool are you using to write code? The code is not aligned properly, making it difficult to read.
3) In your solution try to use the code written. Like for in this exercise, the exception raised for file not read properly needs to be shown in main file by passing a certain file's path since its a check that we have implemented. This way all code is seen working.

For this exercise : 
1)  in objectify.rb
@file_content ||= get_content unless defined? @file_content
Do we need this unless condition? if yes, why?
2) display_values method is not used anywhere then why is it defined?
3) we can set more things in initialise itself instead of doing it later like class name from file name. Lets target such optimisations for good programming habits. less code is good code maintaining readability of course.

Give a detailed look at the code and reframe it. Lets not just focus on functionality but also good quality.

**Comment by osifoanosike** [comment]
Thanks, i've fixed the indentation and code structure
1. Yes, i think we need the unless condition, so as to check that @file_content is defined. From what i read, i understanding that its best practice for implementing memoization.
2. I misunderstood the question, i thought the functionality of just displaying values was needed.

I also restructured some code 
Thanks

**Comment by mkangia** [comment]
Osifo, this looks better. Code seems better aligned and great that you got class name in initialise itself.
Though i am still missing an option to pass file name as option. Plus i ran this on my machine. Obviously the file was missing so i got a message for file missing but the code still proceeded. Try to get the same on your machine by removing the file and handle this scenario.

For memoization just try without the unless condition and see if it still works?

Plus in main, lets make the attempt twice : once with missing file and once with a file present to have a view of both failed and success scenarios.

**Comment by osifoanosike** [comment]
Removed unless, and it worked fine.
Also updated the logic to use relative file paths and  improved on the exception handling

**Comment by mkangia** [comment]
Now thats a submission :+1:  .. So much better Osifo. Just something better in terms of user experience can be made like when there is no file name given it should prompt me again to enter it or give a better message that the file name was not given instead of saying that file in missing.

But much better than the first submit. Lets keep these things in mind for further exercises Osifo. Better approaches as a developer :100:

**Comment by osifoanosike** [comment]
Thanks much. I've made a UX improvement on the exception message.
